export const data = [
  {
    id: 1,
    first_name: 'Wilmette',
    last_name: 'Maasz',
    email: 'wmaasz0@jalbum.net',
    phone: '130-309-6439',
    Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 2,
    first_name: 'Morry',
    last_name: 'Heater',
    email: 'mheater1@yale.edu',
    phone: '814-809-2958',
        Address:'Ramallah',
    BloodType:'A+',
    Pre:'50%',
  },
  {
    id: 3,
    first_name: 'Laverne',
    last_name: 'MacMorland',
    email: 'lmacmorland2@webnode.com',
    phone: '271-342-7249',
        Address:'Jenen',
    BloodType:'A+',
    Pre:'54%',
  },
  {
    id: 4,
    first_name: 'Cindee',
    last_name: 'De Freitas',
    email: 'cdefreitas3@privacy.gov.au',
    phone: '617-624-6967',
        Address:'Nablus',
    BloodType:'AB+',
    Pre:'90%',

  },
  {
    id: 5,
    first_name: 'Carole',
    last_name: 'Reffe',
    email: 'creffe4@nih.gov',
    phone: '738-966-3137',
        Address:'Nablus',
    BloodType:'A+',
    Pre:'23%',

  },
  {
    id: 6,
    first_name: 'Ansel',
    last_name: 'Iwanicki',
    email: 'aiwanicki5@pagesperso-orange.fr',
    phone: '716-371-2467',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'51%',

  },
  {
    id: 7,
    first_name: 'Herold',
    last_name: 'Mungham',
    email: 'hmungham6@goodreads.com',
    phone: '659-298-5396',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 8,
    first_name: 'Sibeal',
    last_name: 'Andreacci',
    email: 'sandreacci7@bloomberg.com',
    phone: '508-876-5450',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'93%',

  },
  {
    id: 9,
    first_name: 'Eustacia',
    last_name: 'Matteuzzi',
    email: 'ematteuzzi8@rakuten.co.jp',
    phone: '953-375-3684',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'91%',

  },
  {
    id: 10,
    first_name: 'Tiebold',
    last_name: 'Powe',
    email: 'tpowe9@dmoz.org',
    phone: '574-154-1045',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 11,
    first_name: 'Deloris',
    last_name: 'Flintoffe',
    email: 'dflintoffea@usa.gov',
    phone: '281-262-2474',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 12,
    first_name: 'Janela',
    last_name: 'Coite',
    email: 'jcoiteb@columbia.edu',
    phone: '241-621-1528',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 13,
    first_name: 'Ines',
    last_name: 'Ginity',
    email: 'iginityc@studiopress.com',
    phone: '924-888-0857',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 14,
    first_name: 'Godfree',
    last_name: 'Bastistini',
    email: 'gbastistinid@pen.io',
    phone: '694-172-1204',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
  {
    id: 15,
    first_name: 'Jazmin',
    last_name: 'Exrol',
    email: 'jexrole@networkadvertising.org',
    phone: '265-313-4188',
        Address:'Nablus',
    BloodType:'B+',
    Pre:'95%',

  },
];



export const data1 = [
  {
    id: 1,
    first_name: 'Wilmette',
    last_name: 'Maasz',
    email: 'wmaasz0@jalbum.net',
    phone: '130-309-6439',
    Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',
  },
  {
    id: 2,
    first_name: 'Morry',
    last_name: 'Heater',
    email: 'mheater1@yale.edu',
    phone: '814-809-2958',
        Address:'Ramallah',
    BloodType:'A+',
    Date:'1/1/2001',

  },
  {
    id: 3,
    first_name: 'Laverne',
    last_name: 'MacMorland',
    email: 'lmacmorland2@webnode.com',
    phone: '271-342-7249',
        Address:'Jenen',
    BloodType:'A+',
    Date:'1/1/2001',

  },
  {
    id: 4,
    first_name: 'Cindee',
    last_name: 'De Freitas',
    email: 'cdefreitas3@privacy.gov.au',
    phone: '617-624-6967',
        Address:'Nablus',
    BloodType:'AB+',
    Date:'1/1/2001',

  },
  {
    id: 5,
    first_name: 'Carole',
    last_name: 'Reffe',
    email: 'creffe4@nih.gov',
    phone: '738-966-3137',
        Address:'Nablus',
    BloodType:'A+',
    Date:'1/1/2001',

  },
  {
    id: 6,
    first_name: 'Ansel',
    last_name: 'Iwanicki',
    email: 'aiwanicki5@pagesperso-orange.fr',
    phone: '716-371-2467',
        Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 7,
    first_name: 'Herold',
    last_name: 'Mungham',
    email: 'hmungham6@goodreads.com',
    phone: '659-298-5396',
        Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 8,
    first_name: 'Sibeal',
    last_name: 'Andreacci',
    email: 'sandreacci7@bloomberg.com',
    phone: '508-876-5450',
        Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 9,
    first_name: 'Eustacia',
    last_name: 'Matteuzzi',
    email: 'ematteuzzi8@rakuten.co.jp',
    phone: '953-375-3684',
        Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 10,
    first_name: 'Tiebold',
    last_name: 'Powe',
    email: 'tpowe9@dmoz.org',
    phone: '574-154-1045',
        Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 11,
    first_name: 'Deloris',
    last_name: 'Flintoffe',
    email: 'dflintoffea@usa.gov',
    phone: '281-262-2474',
        Address:'Nablus',
    BloodType:'B+',
  },
  {
    id: 12,
    first_name: 'Janela',
    last_name: 'Coite',
    email: 'jcoiteb@columbia.edu',
    phone: '241-621-1528',
        Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 13,
    first_name: 'Ines',
    last_name: 'Ginity',
    email: 'iginityc@studiopress.com',
    phone: '924-888-0857',
    Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 14,
    first_name: 'Godfree',
    last_name: 'Bastistini',
    email: 'gbastistinid@pen.io',
    phone: '694-172-1204',
    Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
  {
    id: 15,
    first_name: 'Jazmin',
    last_name: 'Exrol',
    email: 'jexrole@networkadvertising.org',
    phone: '265-313-4188',
    Address:'Nablus',
    BloodType:'B+',
    Date:'1/1/2001',

  },
];